# Generated by Django 5.1.7 on 2025-05-20 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_parenting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('specialization', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 20, 8, 52, 10, 152285, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
