# Generated by Django 5.1.7 on 2025-05-20 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_parenting', '0005_remove_sessionpermission_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='open_for_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SessionPermission',
        ),
    ]
