# Generated by Django 5.1.7 on 2025-05-20 20:09

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_parenting', '0007_teachingaid_appointment_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teachingaid',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='teaching-aids', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv', 'mov'])]),
        ),
        migrations.AlterField(
            model_name='teachingaid',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachingaid',
            name='youtube_iframe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
