# Generated by Django 5.1.7 on 2025-05-21 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_parenting', '0010_alter_session_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default=datetime.datetime(2025, 5, 21, 9, 15, 18, 34520, tzinfo=datetime.timezone.utc), max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='visiting_hour_from',
            field=models.TimeField(default=datetime.datetime(2025, 5, 21, 9, 15, 25, 105170, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='visiting_hour_to',
            field=models.TimeField(default=datetime.datetime(2025, 5, 21, 9, 15, 31, 360397, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=300),
        ),
    ]
