# Generated by Django 5.1.7 on 2025-05-22 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_parenting', '0012_appointment_time_alter_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 5, 22, 10, 58, 36, 643153, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(),
        ),
    ]
