# Generated by Django 5.1.7 on 2025-05-22 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_parenting', '0013_session_time_alter_session_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='smart_parenting.appointment'),
            preserve_default=False,
        ),
    ]
