# Generated by Django 5.1.7 on 2025-05-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_parenting', '0014_session_appointment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'time')},
        ),
    ]
