# Generated by Django 5.1.7 on 2025-05-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_parenting', '0015_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'date', 'time')},
        ),
    ]
