# Generated by Django 5.1.7 on 2025-05-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_parenting', '0016_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='weekends',
            field=models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=5),
        ),
    ]
