# Generated by Django 5.1.7 on 2025-05-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_parenting', '0017_doctor_weekends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='weekends',
            new_name='weekend',
        ),
    ]
