# Generated by Django 5.1.7 on 2025-05-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_parenting', '0018_rename_weekends_doctor_weekend'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='duration',
            field=models.PositiveIntegerField(default=60, help_text='In minutes'),
        ),
    ]
