# Generated by Django 5.1.7 on 2025-08-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_parenting', '0019_doctor_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingaid',
            name='descrpiton',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='duration',
            field=models.PositiveIntegerField(default=60, verbose_name='Duration (in minutes)'),
        ),
    ]
