# Generated by Django 5.1.7 on 2025-08-06 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_parenting', '0020_teachingaid_descrpiton_alter_doctor_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachingaid',
            name='youtube_iframe',
        ),
    ]
