# Generated by Django 5.1.7 on 2025-08-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_parenting', '0021_remove_teachingaid_youtube_iframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingaid',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
