# Generated by Django 5.1.7 on 2025-08-06 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_parenting', '0022_teachingaid_youtube_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachingaid',
            old_name='descrpiton',
            new_name='description',
        ),
    ]
