# Generated by Django 5.1.7 on 2025-08-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_parenting', '0023_rename_descrpiton_teachingaid_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=14)),
                ('details', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='emergencies')),
            ],
        ),
    ]
