# Generated by Django 5.1.7 on 2025-08-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_parenting', '0024_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='live_location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
