# Generated by Django 5.1.7 on 2025-08-07 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_parenting', '0025_emergency_live_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
