# Generated by Django 5.1.7 on 2025-08-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_parenting', '0027_emergency_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutismScreeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('age', models.CharField(choices=[('INFANTS', 'Infants (6-12 months)'), ('TODDLERS', 'Toddlers (12-24 months)'), ('PRESCHOOLERS', 'Preschoolers (2-5 years)'), ('CHILDREN', 'Children (6-12 years)')], default='INFANTS', max_length=20)),
            ],
        ),
    ]
