# Generated by Django 5.1.7 on 2025-08-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_parenting', '0028_autismscreeningquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='autismscreeningquestion',
            name='expected_answer',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('DOESNT_MATTER', "Doesn't matter")], default='DOESNT_MATTER', max_length=15),
        ),
    ]
