# Generated by Django 5.1.7 on 2025-08-09 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_parenting', '0029_autismscreeningquestion_expected_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autismscreeningquestion',
            name='expected_answer',
        ),
        migrations.AddField(
            model_name='autismscreeningquestion',
            name='is_low_weight',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='autismscreeningquestion',
            name='age',
            field=models.CharField(choices=[('INFANTS', 'Infants (6-12 months)'), ('TODDLERS', 'Toddlers (12-24 months)'), ('PRESCHOOLERS', 'Preschoolers (2-5 years)'), ('CHILDREN', 'Children (6-12 years)')], default='YES', max_length=20),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='smart_parenting.autismscreeningquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
