# Generated by Django 5.1.7 on 2025-08-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_parenting', '0030_remove_autismscreeningquestion_expected_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autismscreeningquestion',
            name='age',
            field=models.CharField(choices=[('INFANTS', 'Infants (6-12 months)'), ('TODDLERS', 'Toddlers (12-24 months)'), ('PRESCHOOLERS', 'Preschoolers (2-5 years)'), ('CHILDREN', 'Children (6-12 years)')], default='INFANTS', max_length=20),
        ),
    ]
