# Generated by Django 5.1.7 on 2025-08-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_parenting', '0031_alter_autismscreeningquestion_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='autismscreeningquestion',
            name='expected_answer',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default='True'),
        ),
    ]
