# Generated by Django 5.1.7 on 2025-08-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_parenting', '0032_autismscreeningquestion_expected_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autismscreeningquestion',
            name='expected_answer',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
