# Generated by Django 5.1.7 on 2025-08-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_parenting', '0033_alter_autismscreeningquestion_expected_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autismscreeningquestion',
            name='is_low_weight',
        ),
        migrations.AddField(
            model_name='autismscreeningquestion',
            name='question_importance',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10),
        ),
    ]
